# Generated by Django 4.0.2 on 2026-02-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactsubmission_creditrating_faqitem_insight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
